implemented kubernates

diff --git a/JENKINSFILE b/JENKINSFILE
--- a/JENKINSFILE
+++ b/JENKINSFILE
@@ -1,38 +1,66 @@
+// pipeline {
+//     agent any
+
+//     environment {
+//         IMAGE_NAME = "snake-game"
+//     }
+//     stages {
+//         stage('Build Maven Project') {
+//             steps {
+//                 bat 'mvn clean package'
+//             }
+//         }
+//         stage('Build Docker Image') {
+//             steps {
+//                 bat 'docker build -t %IMAGE_NAME% .'
+//             }
+//         }
+//         stage('Remove Old Container') {
+//             steps {
+//                 bat 'docker rm -f %CONTAINER_NAME% || exit 0'
+//             }
+//         }
+//         stage('Run Container') {
+//             steps {
+//                 bat 'docker run -d --name %CONTAINER_NAME% %IMAGE_NAME%'
+//             }
+//         }
+//     }
+//     post {
+//         success {
+//             echo 'Pipeline executed successfully!'
+//         }
+//         failure {
+//             echo 'Pipeline failed!'
+//         }
+//     }
+// }
 pipeline {
     agent any
 
     environment {
         IMAGE_NAME = "snake-game"
-        CONTAINER_NAME = "snake-container"
     }
+
     stages {
-        stage('Build Maven Project') {
-            steps {
-                bat 'mvn clean package'
-            }
-        }
+
         stage('Build Docker Image') {
             steps {
                 bat 'docker build -t %IMAGE_NAME% .'
             }
         }
-        stage('Remove Old Container') {
+
+        stage('Load Image into Minikube') {
             steps {
-                bat 'docker rm -f %CONTAINER_NAME% || exit 0'
+                bat 'minikube image load %IMAGE_NAME%'
             }
         }
-        stage('Run Container') {
+
+        stage('Deploy to Kubernetes') {
             steps {
-                bat 'docker run -d --name %CONTAINER_NAME% %IMAGE_NAME%'
+                bat 'kubectl apply -f deployment.yaml'
+                bat 'kubectl apply -f service.yaml'
             }
-        }
-    }
-    post {
-        success {
-            echo 'Pipeline executed successfully!'
-        }
-        failure {
-            echo 'Pipeline failed!'
         }
     }
 }
